CREATE TABLE IF NOT EXISTS Users (
    Id UUID PRIMARY KEY,
    Username TEXT NOT NULL,
    ConnectedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ChatRooms (
    Id UUID PRIMARY KEY,
    Name TEXT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Messages (
    Id UUID PRIMARY KEY,
    Content TEXT NOT NULL,
    SentAt TIMESTAMP NOT NULL,
    UserId UUID NOT NULL REFERENCES Users(Id),
    ChatRoomId UUID NOT NULL REFERENCES ChatRooms(Id)
);


INSERT INTO Users (Id, Username, ConnectedAt)
VALUES ('11112222-3333-4444-5555-666677778888', 'Juan', CURRENT_TIMESTAMP);

INSERT INTO ChatRooms (Id, Name, CreatedAt)
VALUES ('a1b2c3d4-e5f6-7890-abcd-1234567890ab', 'General', CURRENT_TIMESTAMP);
